language: generic

matrix:
  allow_failures:
    - os: windows
  include:
    - os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      env:
        - PYTHON=2.7 PYTHONWARNINGS=ignore
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
      before_install:
        - choco install miniconda2 openssl.light
        - conda create -n test-environment python=$PYTHON --yes
        - . activate test-environment
        - conda --version ; python --version ; pip --version
        - python -m pip install --upgrade pip

    - os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      env:
        - PYTHON=3.5 PYTHONWARNINGS=ignore
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
      before_install:
        - choco install miniconda3 openssl.light
        - conda create -n test-environment python=$PYTHON --yes
        - . activate test-environment
        - conda --version ; python --version ; pip --version
        - python -m pip install --upgrade pip

script: conda --version ; python --version ; pip --version
